cloud_scale_data_platform:
  target: local
  outputs:
    local:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'platform') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'platform') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'data_platform') }}"
      schema: analytics
      threads: 4

