"""Run the full test suite under coverage and generate a markdown evidence
report — evidence/validation/test-coverage-report.md.

Runs pytest with pytest-cov, writing a JSON coverage report to a temp file,
then reshapes that into a sorted-by-coverage markdown table plus a summary,
so the actual coverage evidence is generated from a real run every time
(deterministic given the same test suite/source, not hand-maintained).

Usage:
    PYTHONPATH=.:services/shared python scripts/generate_coverage_report.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "evidence" / "validation" / "test-coverage-report.md"

COVERAGE_SOURCES = ["services", "scripts", "platform_cli", "data_products", "lineage", "reliability"]

# Areas of the codebase deliberately excluded from the audited --source list
# (and why) — kept here so the generated report can state this explicitly
# rather than silently omitting them.
EXCLUDED_AREAS = {
    "spark/streaming, spark/jobs": (
        "Measured separately by tests/streaming/ (40 tests) — PySpark's own "
        "subprocess/JVM execution model doesn't play well with coverage.py's "
        "instrumentation in the same run as the rest of the suite."
    ),
    "sdk/python, kafka/, airflow/": (
        "Thin wrappers/DAG definitions exercised by their own dedicated "
        "tests (tests/test_platform_hardening_tooling.py, "
        "tests/test_airflow_dags.py) but not included in this line-coverage "
        "sweep."
    ),
}


def run_coverage() -> dict:
    with tempfile.TemporaryDirectory() as tmp_dir:
        json_path = Path(tmp_dir) / "coverage.json"
        cov_source_args = [f"--cov={src}" for src in COVERAGE_SOURCES]
        cmd = [
            sys.executable,
            "-m",
            "pytest",
            *cov_source_args,
            f"--cov-report=json:{json_path}",
            "--cov-report=",
            "-q",
        ]
        env = os.environ.copy()
        # coverage.py's own data file (.coverage*) can't be written in the
        # project root in some sandboxed environments (permission denied on
        # the temp-then-rename it does internally) — redirect it to the
        # same temp dir as the JSON report, which is always writable.
        env["COVERAGE_FILE"] = str(Path(tmp_dir) / ".coverage")
        result = subprocess.run(cmd, cwd=PROJECT_ROOT, env=env, capture_output=True, text=True)
        if result.returncode not in (0, 1):  # 1 = tests failed but coverage still ran; anything else is a real error
            raise RuntimeError(f"coverage run failed (exit {result.returncode}):\n{result.stdout}\n{result.stderr}")
        return json.loads(json_path.read_text())


def generate_report_markdown(coverage_data: dict) -> str:
    files = coverage_data["files"]
    totals = coverage_data["totals"]

    rows = []
    for path, data in files.items():
        summary = data["summary"]
        rows.append(
            {
                "path": path,
                "statements": summary["num_statements"],
                "missing": summary["missing_lines"],
                "percent": summary["percent_covered"],
            }
        )
    rows.sort(key=lambda r: r["percent"])

    lines = [
        "# Test Coverage Report",
        "",
        "Generated by `scripts/generate_coverage_report.py` (pytest-cov, a",
        "real run of the full suite — not hand-maintained). Regenerate with",
        "`make coverage-report`.",
        "",
        f"**Overall: {totals['percent_covered']:.1f}%** "
        f"({totals['covered_lines']}/{totals['num_statements']} statements) "
        f"across {len(files)} files in `{', '.join(COVERAGE_SOURCES)}`.",
        "",
        "## Excluded From This Sweep",
        "",
    ]
    for area, reason in EXCLUDED_AREAS.items():
        lines.append(f"- **{area}**: {reason}")
    lines.append("")

    lines.append("## Lowest-Coverage Files (bottom 25)")
    lines.append("")
    lines.append("| File | Statements | Missing | Coverage |")
    lines.append("| --- | ---: | ---: | ---: |")
    for row in rows[:25]:
        lines.append(f"| `{row['path']}` | {row['statements']} | {row['missing']} | {row['percent']:.0f}% |")
    lines.append("")

    lines.append("## Fully Covered Files (100%)")
    lines.append("")
    fully_covered = [r["path"] for r in rows if r["percent"] == 100.0 and r["statements"] > 0]
    lines.append(f"{len(fully_covered)} files at 100% coverage.")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    coverage_data = run_coverage()
    report = generate_report_markdown(coverage_data)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(report)
    print(f"generated coverage report: {OUTPUT_PATH}")
    print(f"overall coverage: {coverage_data['totals']['percent_covered']:.1f}%")


if __name__ == "__main__":
    main()
